/* EDIT PAGE */

// Shows/hides spinner, indicates when webapp is saving changes
var toggleSpinner = function (isDone) {
    // spinner glyphicon glyphicon-ok
    if (isDone) {
        $("#updateState")
            .removeClass("glyphicon-refresh")
            .removeClass("spinner")
            .addClass("glyphicon-ok");
    } else {
        $("#updateState")
            .removeClass("glyphicon-ok")
            .addClass("glyphicon-refresh")
            .addClass("spinner");
    }
}

// on product/quantity change, update unit price and total price in view
var updatePrices = function () {
    var total = 0;
    $("select[name^='OrderDetail']").each(function (index) {
        var productID = $(this).val();
        var unitPrice = $("input[name='" + productID + "']").val();
        unitPrice = unitPrice.replace(",", ".");

        var quantity = $("input[name='OrderDetail[" + index + "].Quantity']").val();

        total += parseFloat(unitPrice * quantity);

        $("label[name='unitPrice[" + index + "]']").text(unitPrice + " $");
    }); 0
    $("#Total").val(total.toFixed(2).replace(",", "."));
};

// update product id and quantity to db
var updateProduct = function () {
    var detailIDholder = $(this).data("detailid");
    var productIDholder = $(this).data("product");
    var quantityHolder = $(this).data("quantity");

    var data = {
        ID: $("[name='" + detailIDholder + "']").val(),
        ProductId: $("[name='" + productIDholder + "']").val(),
        OrderId: $("#ID").val(),
        Quantity: $("[name='" + quantityHolder + "']").val(),
        __RequestVerificationToken: $('input[name="__RequestVerificationToken"]').val()
    };

    var link = $(this).data("url");

    toggleSpinner(false);
    $.post(link, data, (response) => {
        console.log(response);
        toggleSpinner(true);
    });
};

// Updates CustomerId and Total values in db
var updateChanges = function () {
    var data = {
        CustomerID: $("#CustomerId").val(),
        Total: $("#Total").val(),
        ID: $("#ID").val(),
        __RequestVerificationToken: $('input[name="__RequestVerificationToken"]').val()
    };
    // link gets generated by an Html helper method, we save the result of that helper method in a hidden field
    var link = $("#editForm").data("url");

    toggleSpinner(false);
    $.post(link, data, (response) => {
        console.log(response);
        // Rerender list at top of page
        rerenderIndex();
        toggleSpinner(true);
    });
};

// add order detail event handler
var addOrderDetail = function () {
    var link = $(this).data("url");
    var data = {
        OrderID: $(this).data("orderid"),
        __RequestVerificationToken: $('input[name="__RequestVerificationToken"]').val()
    };
    toggleSpinner(false);
    $.post(link, data, function (response) {
        $("#orderDetails").html(response);
        // re-attach eventHandlers
        setup();
        // Update new Total
        updateChanges();
        // Rerender list at top of page
        rerenderIndex();
        toggleSpinner(true);
    });
};

// Remove Order detail event handler
var removeOrderDetail = function () {
    var link = $(this).data("url");
    var data = {
        OrderID: $(this).data("orderid"),
        RemoveId: $(this).data("removeid"),
        __RequestVerificationToken: $('input[name="__RequestVerificationToken"]').val()
    };
    toggleSpinner(false);
    $.post(link, data, function (response) {
        $("#orderDetails").html(response);
        // re-attach eventHandlers
        setup();
        // Update new Total
        updateChanges();
        // Rerender list at top of page
        rerenderIndex();
        toggleSpinner(true);
    });
};

// This method gets fired every time the partial view with order details in the Edit page gets rerendered
var setup = function () {
    // Event Handlers to Add/Remove Order Details
    $("span[id^='Remove[']").each(function () {
        $(this).click(removeOrderDetail.bind(this));
    });
    $("#AddOrderDetail").click(addOrderDetail);
    // change product in order
    $("select[name^='OrderDetail']").change(updateProduct);
    $("select[name^='OrderDetail']").change(updatePrices);
    $("select[name^='OrderDetail']").change(updateChanges);
    // change quantity of a product in order
    $("input[type='number'][name^='OrderDetail']").change(updateProduct);
    $("input[type='number'][name^='OrderDetail']").change(updatePrices);
    $("input[type='number'][name^='OrderDetail']").change(updateChanges);
    // Calculate total and show Unit Price for each order
    updatePrices();
};

/* INDEX PAGE */

var rerenderIndex = function () {
    $.post($("#OrderList").data("url"), null, function (response) {
        $("#OrderList").html(response);
        setIndexEvents();
        toggleSpinner(true);
    });
};

var setIndexEvents = function () {
    // Details buttons
    $("span[id^='Details_']").click(function () {
        var link = $(this).data("url");
        var data = {
            id: $(this).data("target")
        };

        $.post(link, data, function (response) {
            $("#partialView").html(response);
        });
    });

    // Edit buttons
    $("span[id^='Edit_']").click(function () {
        var link = $(this).data("url");
        var data = {
            id: $(this).data("target")
        };

        $.post(link, data, function (response) {
            $("#partialView").html(response);
            // first time setup
            setup();
            // Update CustomerId and Total on value change
            $("#CustomerId").change(updateChanges);
        });
    });
};

// Add event handlers to our buttons to show our partial views
// This gets fired the very first time you visit the Index page
$(function () {
    setIndexEvents();
});